spring:
  application:
    name: user-aggregation-service
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

data-sources:
  - name: data-base-1
    strategy: postgres
    url: jdbc:postgresql://postgres1:5432/db1
    table: users
    user: testuser
    password: testpass
    mapping:
      id: id
      username: username
      name: name
      surname: surname
  - name: data-base-2
    strategy: postgres
    url: jdbc:postgresql://postgres2:5432/db2
    table: user_table
    user: testuser
    password: testpass
    mapping:
      id: ldap_login
      username: ldap_login
      name: name
      surname: surname